volumes:
  db:

services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: find-a-friend
    ports:
      - 5432:5432
    volumes:
      - db:/bitnami/postgresql
